# Generated by Django 5.0.7 on 2024-08-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
